//! Wokwi project files generated from `board.toml` (D-025): the `fw` stage writes them next to
//! `board_pins.h` whenever a pin has a `sim` part, and `sim --wokwi` runs them.
//!
//! - `diagram.json`: an ESP32-S3-DevKitC-1 set up as the module (16 MB flash, 8 MB octal PSRAM,
//!   USB Serial/JTAG console) with one stand-in part per `sim` pin, wired as the board has it.
//! - `wokwi.toml`: points at the `build-wokwi` image (`flasher_args.json`, so the custom
//!   partition table is used).
//! - `wokwi-selftest.yaml`: the scenario: each `[[sim.wokwi_step]]`, then `SELFTEST_DONE`.
//!
//! Wokwi pauses the simulation between scenario steps (every step is a pause point in
//! wokwi-cli 0.27.1), so a `wait` can't miss a line printed while a button is held, as long as the
//! firmware prints it only after the release.

use serde_json::{Value, json};

use crate::boardfile::{BoardFile, SimPart};

pub const DIAGRAM: &str = "diagram.json";
pub const TOML: &str = "wokwi.toml";
pub const SCENARIO: &str = "wokwi-selftest.yaml";
/// The ESP-IDF project name (`project(firmware)` in the template's CMakeLists.txt).
const ELF: &str = "build-wokwi/firmware.elf";
/// A press without `hold_ms`.
const PRESS_MS: u64 = 200;

/// True if the board has anything for Wokwi to drive or check.
pub fn wanted(bf: &BoardFile) -> bool {
    bf.pins.iter().any(|p| p.sim.is_some())
}

/// The id of the part standing in for a signal (`BOOT` → `boot`).
fn part_id(signal: &str) -> String {
    signal.to_lowercase()
}

pub fn diagram(bf: &BoardFile) -> String {
    let mut parts: Vec<Value> = vec![json!({
        "type": "board-esp32-s3-devkitc-1",
        "id": "esp",
        "top": 0,
        "left": 0,
        "attrs": {
            "flashSize": "16",
            "psramSize": "8",
            "psramType": "octal",
            "serialInterface": "USB_SERIAL_JTAG",
            "cpuFrequency": "240",
        },
    })];
    let mut wires: Vec<Value> = vec![];
    let mut wire = |a: String, b: &str| wires.push(json!([a, b, "green", []]));
    let mut row = 0;
    let mut place = |parts: &mut Vec<Value>, kind: &str, id: &str, attrs: Value| {
        parts.push(json!({"type": kind, "id": id, "top": row * 80, "left": 260, "attrs": attrs}));
        row += 1;
    };
    let mut rgb = false;
    for pin in &bf.pins {
        let Some(sim) = pin.sim else { continue };
        let id = part_id(&pin.signal);
        let esp = format!("esp:{}", pin.gpio);
        match sim {
            // pushbutton to GND with a 10k pull-up, like a board's button
            SimPart::Button => {
                place(&mut parts, "wokwi-pushbutton", &id, json!({"label": pin.signal, "bounce": "0"}));
                place(&mut parts, "wokwi-resistor", &format!("{id}_pullup"), json!({"value": "10000"}));
                wire(esp.clone(), &format!("{id}:1.l"));
                wire(format!("{id}:2.l"), "esp:GND.1");
                wire(esp, &format!("{id}_pullup:1"));
                wire(format!("{id}_pullup:2"), "esp:3V3.1");
            }
            // pin → 1k → LED → GND
            SimPart::Led => {
                place(&mut parts, "wokwi-resistor", &format!("{id}_r"), json!({"value": "1000"}));
                place(&mut parts, "wokwi-led", &id, json!({"color": "red", "label": pin.signal}));
                wire(esp, &format!("{id}_r:1"));
                wire(format!("{id}_r:2"), &format!("{id}:A"));
                wire(format!("{id}:C"), "esp:GND.1");
            }
            // one cathode of the common-anode RGB LED, anode on 3V3
            SimPart::LedR | SimPart::LedG | SimPart::LedB => {
                if !rgb {
                    place(&mut parts, "wokwi-rgb-led", "rgb", json!({"common": "anode"}));
                    wire("rgb:COM".into(), "esp:3V3.1");
                    rgb = true;
                }
                let leg = match sim {
                    SimPart::LedR => "R",
                    SimPart::LedG => "G",
                    _ => "B",
                };
                wire(esp, &format!("rgb:{leg}"));
            }
            // wiper on the pin; the scenario can turn it (an analog input such as a battery divider)
            SimPart::Pot => {
                place(&mut parts, "wokwi-potentiometer", &id, json!({}));
                wire(format!("{id}:VCC"), "esp:3V3.1");
                wire(format!("{id}:GND"), "esp:GND.1");
                wire(format!("{id}:SIG"), &esp);
            }
        }
    }
    let d = json!({
        "version": 1,
        "author": "pcbgen, from board.toml (do not edit; the fw stage rewrites it)",
        "editor": "wokwi",
        "parts": parts,
        "connections": wires,
        "dependencies": {},
    });
    serde_json::to_string_pretty(&d).unwrap() + "\n"
}

pub fn toml() -> String {
    format!(
        "# Generated by pcbgen from board.toml; do not edit. `sim --wokwi` builds build-wokwi.\n\
         [wokwi]\nversion = 1\nfirmware = 'build-wokwi/flasher_args.json'\nelf = '{ELF}'\n"
    )
}

/// A YAML double-quoted scalar (JSON's string syntax is valid YAML).
fn q(s: &str) -> String {
    Value::from(s).to_string()
}

pub fn scenario(bf: &BoardFile) -> String {
    let mut y = format!(
        "# Generated by pcbgen from board.toml [[sim.wokwi_step]]; do not edit.\n\
         name: {}\nversion: 1\nauthor: pcbgen\nsteps:\n",
        q(&format!("{} self-test", bf.board.name))
    );
    let pin = |sig: &str| bf.pins.iter().find(|p| p.signal == sig);
    for st in &bf.sim.wokwi_steps {
        y += &format!("  - wait-serial: {}\n", q(&st.wait));
        if let Some(sig) = &st.press {
            let id = q(&part_id(sig));
            let ms = st.hold_ms.unwrap_or(PRESS_MS);
            y += &format!("  - set-control:\n      part-id: {id}\n      name: pressed\n      value: 1\n");
            y += &format!("  - delay: {ms}ms\n");
            y += &format!("  - set-control:\n      part-id: {id}\n      name: pressed\n      value: 0\n");
        }
        if let (Some(sig), Some(level)) = (&st.expect, st.level) {
            // the gate guarantees the signal exists; read the module's pin, not the part's
            let gpio = pin(sig).map_or(0, |p| p.gpio);
            y += &format!("  - expect-pin:\n      part-id: esp\n      pin: {}\n      value: {level}\n", q(&gpio.to_string()));
        }
    }
    y += "  - wait-serial: \"SELFTEST_DONE\"\n";
    y
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::boardfile::parse;

    const BOARD: &str = r#"
[board]
name = "t"
revision = "A"
module = "U1"

[[pin]]
signal = "BOOT"
pin = "IO0"
net = "BOOT"
gpio = 0
dir = "in"
active_low = true
sim = "button"

[[pin]]
signal = "LED"
pin = "IO48"
net = "LED"
gpio = 48
dir = "out"
sim = "led"

[[pin]]
signal = "RED"
pin = "IO8"
net = "RED"
gpio = 8
dir = "out"
sim = "led_r"

[[pin]]
signal = "GREEN"
pin = "IO9"
net = "GREEN"
gpio = 9
dir = "out"
sim = "led_g"

[[pin]]
signal = "VBAT"
pin = "IO4"
net = "VBAT"
gpio = 4
dir = "in"
sim = "pot"

[[pin]]
signal = "SDA"
pin = "IO1"
net = "SDA"
gpio = 1
dir = "io"

[power]
source = "USB"
budget_ma = 500

[[sim.wokwi_step]]
wait = "SELFTEST_LOOK led on"
expect = "LED"
level = 1

[[sim.wokwi_step]]
wait = "SELFTEST_PRESS \"boot\""
press = "BOOT"
hold_ms = 1200
"#;

    #[test]
    fn diagram_wires_each_sim_part() {
        let bf = parse(BOARD).unwrap();
        assert!(wanted(&bf));
        let d: Value = serde_json::from_str(&diagram(&bf)).unwrap();
        let ids: Vec<&str> = d["parts"].as_array().unwrap().iter().map(|p| p["id"].as_str().unwrap()).collect();
        assert_eq!(ids, ["esp", "boot", "boot_pullup", "led_r", "led", "rgb", "vbat"]);
        assert_eq!(d["parts"][0]["attrs"]["psramType"], "octal");
        let wires: Vec<(String, String)> = d["connections"]
            .as_array()
            .unwrap()
            .iter()
            .map(|w| (w[0].as_str().unwrap().to_string(), w[1].as_str().unwrap().to_string()))
            .collect();
        let has = |a: &str, b: &str| wires.iter().any(|(x, y)| x == a && y == b);
        assert!(has("esp:0", "boot:1.l") && has("boot:2.l", "esp:GND.1") && has("boot_pullup:2", "esp:3V3.1"));
        assert!(has("esp:48", "led_r:1") && has("led_r:2", "led:A") && has("led:C", "esp:GND.1"));
        assert!(has("rgb:COM", "esp:3V3.1") && has("esp:8", "rgb:R") && has("esp:9", "rgb:G"));
        assert_eq!(wires.iter().filter(|(a, _)| a == "rgb:COM").count(), 1);
        assert!(has("vbat:SIG", "esp:4"));
        // SDA has no sim part
        assert!(!wires.iter().any(|(a, b)| a == "esp:1" || b == "esp:1"));
    }

    #[test]
    fn scenario_steps_then_done() {
        let bf = parse(BOARD).unwrap();
        let s = scenario(&bf);
        let want = "  - wait-serial: \"SELFTEST_LOOK led on\"\n  - expect-pin:\n      part-id: esp\n      pin: \"48\"\n      value: 1\n\
                    \x20 - wait-serial: \"SELFTEST_PRESS \\\"boot\\\"\"\n  - set-control:\n      part-id: \"boot\"\n      name: pressed\n      value: 1\n\
                    \x20 - delay: 1200ms\n  - set-control:\n      part-id: \"boot\"\n      name: pressed\n      value: 0\n\
                    \x20 - wait-serial: \"SELFTEST_DONE\"\n";
        assert!(s.ends_with(want), "{s}");
        assert!(s.contains("name: \"t self-test\"\nversion: 1\n"));
    }

    #[test]
    fn no_sim_parts_no_wokwi() {
        let pins_only = BOARD.split("[[sim.wokwi_step]]").next().unwrap().replace("sim = \"", "# sim = \"");
        let bf = parse(&pins_only).unwrap();
        assert!(!wanted(&bf));
    }
}
