// Generated by pcbgen from board.toml; do not edit. Regenerate with the `fw` stage.
#pragma once

#include "driver/gpio.h"

#define BOARD_NAME "starter"
#define BOARD_REVISION "0"

// I2C_SDA: module pin IO1, net I2C_SDA, io; SHT40 at 0x44 and the Qwiic port; 4.7k pull-up (R7)
#define PIN_I2C_SDA GPIO_NUM_1

// I2C_SCL: module pin IO2, net I2C_SCL, out; 4.7k pull-up (R8)
#define PIN_I2C_SCL GPIO_NUM_2

// STATUS_LED: module pin IO48, net STATUS, out; red LED D2 through 1k (R6); high = on
#define PIN_STATUS_LED GPIO_NUM_48

// BOOT: module pin IO0, net BOOT, in, active low; BOOT button SW2, 10k pull-up (R5); strapping pin: held low at reset = download mode
#define PIN_BOOT GPIO_NUM_0
#define PIN_BOOT_ACTIVE_LOW 1

// UART_TX: module pin TXD0, net UART_TX, out; test point TP4; boot log
#define PIN_UART_TX GPIO_NUM_43

// UART_RX: module pin RXD0, net UART_RX, in; test point TP5
#define PIN_UART_RX GPIO_NUM_44

// USB_DM: module pin USB_D-, net USB_D-, io; native USB (flashing and serial console)
#define PIN_USB_DM GPIO_NUM_19

// USB_DP: module pin USB_D+, net USB_D+, io; native USB (flashing and serial console)
#define PIN_USB_DP GPIO_NUM_20

// Self-tests the firmware runs at bring-up: static const char *t[] = BOARD_SELF_TESTS;
#define BOARD_SELF_TEST_COUNT 4
#define BOARD_SELF_TESTS {"sht40", "i2c_scan", "status_led", "boot_button"}
