// Generated by pcbgen from board.toml; do not edit. Regenerate with the `fw` stage.
#pragma once

#include "driver/gpio.h"

#define BOARD_NAME "capture-clip"
#define BOARD_REVISION "A"

// BUTTON: module pin IO0, net BUTTON_N, in, active low; main button SW1 to GND, 10k pull-up (R8); deep-sleep wake (ext1, any low); strapping pin: held low at a full reset = download mode
#define PIN_BUTTON GPIO_NUM_0
#define PIN_BUTTON_ACTIVE_LOW 1

// BAT_ADC: module pin IO1, net BAT_ADC, in; cell voltage / 3 (R13 + R14 over R15, 100n C9); ADC1_CH0 at 6 dB; read at rest, averaged
#define PIN_BAT_ADC GPIO_NUM_1

// VBUS_SENSE: module pin IO2, net VBUS_SENSE, in; USB 5 V x 0.6 (R16 100k over R17 150k): high = USB present; deep-sleep wake (ext0, high)
#define PIN_VBUS_SENSE GPIO_NUM_2

// CHRG: module pin IO4, net CHRG_SENSE, in, active low; TP4057 CHRG (open drain, low while charging) through 100k (R5); never an internal pull-up (a low would read as ~2.4 V); the charge light pulls it high
#define PIN_CHRG GPIO_NUM_4
#define PIN_CHRG_ACTIVE_LOW 1

// STDBY: module pin IO5, net STDBY_N, in, active low; TP4057 STDBY (open drain, low when the charge is complete); internal pull-up only while VBUS_SENSE is high, off before sleep
#define PIN_STDBY GPIO_NUM_5
#define PIN_STDBY_ACTIVE_LOW 1

// MIC_PWR: module pin IO6, net MIC_PWR, out; the microphone's VDD through R18 (0 ohm), about 0.5 mA; high = on; stop and ground SCK/WS before switching it off; held low in sleep
#define PIN_MIC_PWR GPIO_NUM_6

// CHG_FAST: module pin IO7, net CHG_FAST_N, out, active low; fast charge: open drain; low = R19 (4.3k) in parallel with R3 on the TP4057's PROG = ~333 mA; released (hi-Z) = 100 mA. Never driven high, no pulls. Released whenever Wi-Fi is on, asleep and at reset
#define PIN_CHG_FAST GPIO_NUM_7
#define PIN_CHG_FAST_ACTIVE_LOW 1

// LED_R: module pin IO8, net LED_R_N, out, active low; red cathode of D4 through 1k (R10); anode on VSYS; low = on; held high in sleep
#define PIN_LED_R GPIO_NUM_8
#define PIN_LED_R_ACTIVE_LOW 1

// LED_G: module pin IO9, net LED_G_N, out, active low; green cathode of D4 through 1k (R11); low = on; held high in sleep
#define PIN_LED_G GPIO_NUM_9
#define PIN_LED_G_ACTIVE_LOW 1

// LED_B: module pin IO10, net LED_B_N, out, active low; blue cathode of D4 through 1k (R12); low = on; held high in sleep
#define PIN_LED_B GPIO_NUM_10
#define PIN_LED_B_ACTIVE_LOW 1

// I2S_SCK: module pin IO11, net I2S_SCK, out; microphone bit clock (1.024 MHz at 16 kHz); held low in sleep
#define PIN_I2S_SCK GPIO_NUM_11

// I2S_WS: module pin IO12, net I2S_WS, out; microphone word select; the mic is the left channel (LR to GND); held low in sleep
#define PIN_I2S_WS GPIO_NUM_12

// I2S_SD: module pin IO13, net I2S_SD, in; microphone data; 100k pull-down (R9)
#define PIN_I2S_SD GPIO_NUM_13

// SPARE_IO21: module pin IO21, net SPARE_IO21, io; spare, on test point TP8 (rework)
#define PIN_SPARE_IO21 GPIO_NUM_21

// UART_TX: module pin TXD0, net UART_TX, out; test point TP6; boot log
#define PIN_UART_TX GPIO_NUM_43

// UART_RX: module pin RXD0, net UART_RX, in; test point TP7
#define PIN_UART_RX GPIO_NUM_44

// USB_DM: module pin USB_D-, net USB_D-, io; native USB (flashing, serial console, provisioning)
#define PIN_USB_DM GPIO_NUM_19

// USB_DP: module pin USB_D+, net USB_D+, io; native USB (flashing, serial console, provisioning)
#define PIN_USB_DP GPIO_NUM_20

// Self-tests the firmware runs at bring-up: static const char *t[] = BOARD_SELF_TESTS;
#define BOARD_SELF_TEST_COUNT 6
#define BOARD_SELF_TESTS {"mic", "led_rgb", "button", "battery", "usb_sense", "wifi"}
